---
# Lint the code base and launch unit test at each push or pull request
name: Lint, Test, Build and Deploy

"on":
  push:
    # execute when pushing only branches and tags
    branches:
      - "**"
      # avoid infinite loop for auto created PRs
      - "!update/pre-commit-*"
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:
  pull_request:
    branches:
      - master
  release:
    types:
      - published

env:
  COND_PUSH_OR_PR: ${{ github.event_name == 'pull_request' || github.event_name == 'push' }}

jobs:
  # -------------------------------------------------------
  # Pre-commit
  # -------------------------------------------------------
  pre-commit:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true # Forces Node 24 runtime
    permissions:
      # needed by guibranco/github-status-action-v2@v1
      statuses: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - uses: actions/create-github-app-token@v3.1.1
        if: ${{ success() }}
        id: generate-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: guibranco/github-status-action-v2@v1
        if: ${{ env.COND_PUSH_OR_PR }}
        with:
          authToken: ${{ secrets.GITHUB_TOKEN }}
          context: lint
          state: pending

      - name: Run pre-commit
        uses: j178/prek-action@v2
        id: preCommit
        with:
          extra-args: >-
            -c .pre-commit-config.yaml -a

      - uses: guibranco/github-status-action-v2@v1
        if: ${{ env.COND_PUSH_OR_PR }}
        with:
          authToken: ${{ secrets.GITHUB_TOKEN }}
          context: lint
          state: ${{ job.status }}

      - name: Create Pull Request
        id: cpr
        if: >
          (
            github.event_name == 'push' ||
            github.event.pull_request.head.repo.full_name ==
            github.repository
          )
          && steps.preCommit.conclusion == 'failure'
          && !contains(github.event.head_commit.message, 'skip fix')
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ steps.generate-token.outputs.token }}
          committer: fchastanet <237869+fchastanet@users.noreply.github.com>
          branch: update/pre-commit-fixes-${{ env.branch_name }}
          delete-branch: true
          title: lint fixes
          commit-message: Auto-update lint fixes
          body: |
            some auto fixes have been generated during pre-commit run
          labels: pre-commit-fixes

      - name: Print Pull request created
        if: |-
          ${{
            steps.cpr.outputs.pull-request-number &&
            steps.cpr.conclusion == 'success'
          }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"

  # -------------------------------------------------------
  # Unit tests
  # -------------------------------------------------------
  unit-tests:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true # Forces Node 24 runtime
    needs:
      - pre-commit
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
    permissions:
      # needed by ouzi-dev/commit-status-updater@v2
      statuses: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          make install
          make install-dev

      - uses: ouzi-dev/commit-status-updater@v2
        with:
          name: test-python-${{ matrix.python-version }}
          status: pending

      - name: Test
        run: |
          make test-all

      - name: Upload coverage reports to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Publish coverage report
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: code-coverage-${{ github.job }}-${{ github.run_number }}-${{ matrix.python-version }}
          path: |
            .coverage
            coverage.xml
            htmlcov/
          include-hidden-files: true
          if-no-files-found: ignore

      - uses: ouzi-dev/commit-status-updater@v2
        with:
          name: test-python-${{ matrix.python-version }}
          status: ${{ job.status }}

  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true # Forces Node 24 runtime
    needs:
      - unit-tests
      - pre-commit
    if: |-
      ${{
        github.event_name == 'release' ||
        (
          github.event_name == 'push' &&
          startsWith(github.ref, 'refs/tags/')
        )
      }}

    permissions:
      contents: write  # needed by svenstaro/upload-release-action and ncipollo/release-action
    environment: Python

    steps:
      - uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Build package
        run: make build

      - name: Check build
        run: twine check dist/*

      - name: Generate changelog
        id: changelog
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          allowUpdates: true
          generateReleaseNotes: true
          draft: false
          prerelease: ${{ contains(github.ref_name, '-') }}

      - name: Upload wheel to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file:
            dist/ai_linter-${{ github.ref_name }}-py3-none-any.whl
          tag: ${{ github.ref }}
          overwrite: true
          asset_name: ai_linter-${{ github.ref_name }}-py3.12.whl

      - name: Publish to PyPI
        if: github.event_name == 'release'
        continue-on-error: true
        env:
          TWINE_USERNAME: ${{ vars.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: twine upload dist/* --verbose --non-interactive --skip-existing
